### ISSUE TITLE
Couldn't build with llama2.c

### ISSUE THREAD

**Issue by wooksong** [nnstreamer/nnstreamer-android#125]
```bash
$ git diff
diff --git a/gradle.properties b/gradle.properties
index f0f88c0..0c317db 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -7,7 +7,7 @@ dir.nnstreamer=nnstreamer
 dir.nnstreamerEdge=nnstreamer-edge
 dir.mlApi=ml-api
 # To use llama2.c uncomment the line below
-# dir.llama2c=llama2.c
+dir.llama2c=llama2.c
 kotlin.code.style=official
 android.useAndroidX=true
 android.enableJetifier=true

$ ./grdalew build
...omitted...
  Caused by: com.android.ide.common.process.ProcessException: Error while executing process /home/wook/Android/Sdk/ndk/25.2.9519653/ndk-build with arguments {APP_BUILD_SCRIPT=/home/wook/Work/NNS/nnstreamer-android/externals/ml-api/java/android/nnstreamer/src/main/jni/Android.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-33 NDK_OUT=/home/wook/Work/NNS/nnstreamer-android/nnstreamer-api/build/intermediates/cxx/Debug/r4y6g183/obj NDK_LIBS_OUT=/home/wook/Work/NNS/nnstreamer-android/nnstreamer-api/build/intermediates/cxx/Debug/r4y6g183/lib NDK_PROJECT_PATH=./ NDK_APPLICATION_MK=/home/wook/Work/NNS/nnstreamer-android/externals/ml-api/java/android/nnstreamer/src/main/jni/Application.mk GSTREAMER_JAVA_SRC_DIR=src/main/java GSTREAMER_ROOT_ANDROID=/home/wook/Work/NNS/nnstreamer-android/externals/gst-1.0-android-universal NNSTREAMER_ROOT=/home/wook/Work/NNS/nnstreamer-android/externals/nnstreamer NNSTREAMER_EDGE_ROOT=/home/wook/Work/NNS/nnstreamer-android/externals/nnstreamer-edge ML_API_ROOT=/home/wook/Work/NNS/nnstreamer-android/externals/ml-api ENABLE_TF_LITE=false ENABLE_LLAMA2C=true LLAMA2C_DIR=/home/wook/Work/NNS/nnstreamer-android/externals/llama2.c APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
        at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:73)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:48)
        at com.android.build.gradle.internal.cxx.process.ExecuteProcessKt.execute(ExecuteProcess.kt:277)
        ... 141 more
  Caused by: org.gradle.process.internal.ExecException: Process 'command '/home/wook/Android/Sdk/ndk/25.2.9519653/ndk-build'' finished with non-zero exit value 2
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:442)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:46)
        ... 142 more
...omitted...
```

It seems that there are missing ```.mk``` files for llama.c.

**Comment by niley7464** [comment]
I tested with `llama2.c` option like [this](https://github.com/niley7464/nnstreamer-android/actions/runs/11887934578), and build was successful with llama2.c.
Could you explain more about your environment 😭 ?

**Comment by wooksong** [comment]
@niley7464 I have discovered what the problem is.

```bash
$ pwd
./nnstreamer-android/externals/llama2.c
$ git remote -v
origin  https://github.com/wooksong/llama2.c.git (fetch)
origin  https://github.com/wooksong/llama2.c.git (push)
upstream        https://github.com/nnsuite/llama2.c.git (fetch)
upstream        https://github.com/nnsuite/llama2.c.git (push)
```
